apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: back-pony-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:3c42ad2d03b24618b2bed7e68509eeb8fe2621cd@sha256:b03b5fa21cf137dbdaf9b187ecce8375bb3150e2e97094a9192f8a082a179599
        name: container-image  
